name: Run Tests

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default_value'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
